### ISSUE TITLE
SYMPHONY 5.6.17 fails to build on linux

### ISSUE THREAD

**Issue by casper-murtonen** [coin-or/SYMPHONY#174]
SYMPHONY 5.6.17 as fetched by coin.install.sh with no other arguments fails to then build on linux.

Osi/src/OsiGlpk/OsiGlpkSolverInterface.cpp references Glpk glp_get_it_cnt(), however glp_get_it_cnt() is absent in Glpk version 4.48 which is fetched by coin.install.sh.  This function first appeared in Glpk 4.53.  Changing glpk_ver to 4.53 is not sufficient as the Makefile explicitly lists all source files, which have changed names.

It appears sufficient to patch this function into 4.48, perhaps by adding the following lines to glpk.patch ([glpk.patch.extra.txt](https://github.com/coin-or/SYMPHONY/files/4391554/glpk.patch.extra.txt)):

```
*** glpk/src/glpk.h.orig        2020-03-27 15:07:16.603852666 +1100
--- glpk/src/glpk.h     2020-03-27 15:06:06.950630344 +1100
***************
*** 1030,1035 ****
--- 1030,1037 ----
  int glp_wclique_exact(glp_graph *G, int v_wgt, double *sol, int v_set);
  /* find maximum weight clique with exact algorithm */
  
+ int glp_get_it_cnt(glp_prob *P);
+ 
  /***********************************************************************
  *  NOTE: All symbols defined below are obsolete and kept here only for
  *        backward compatibility.
*** glpk/src/glpapi06.c.orig    2020-03-27 15:07:02.323602077 +1100
--- glpk/src/glpapi06.c 2020-03-27 15:05:37.858119772 +1100
***************
*** 803,806 ****
--- 803,811 ----
        return k;
  }
  
+ int glp_get_it_cnt(glp_prob *P)
+ {     /* get simplex solver iteration count */
+     return P->it_cnt;
+ }
+ 
  /* eof */

```

**Comment by tkralphs** [comment]
So first, the INSTALL instructions have changed a bit. There is a new and improved script for building and installing called [coinbrew](https://github.com/coin-or/coinbrew). The instructions are updated in the README for stable/5.6, but I haven't made a new release, since nothing else has changed. 

The code is built and tested on Linux with Travis and I don't see any failures there. Here is the latest build in stable/5.6: https://travis-ci.org/github/coin-or/SYMPHONY/jobs/584419444. So something strange is going on. I'm testing locally here. Can you try building stable/5.6 with coinbrew and see if that works?

**Comment by tkralphs** [comment]
Upon digging in a little bit, it seems you are building against the `master` version of Osi, which is the only one that references `glp_get_it_cnt()`. SYMPHONY 5.6 depends on Osi stable version `0.108` and that is what should be downloaded by the install script. It's possible `coin.install.sh` has a bug in it, but if you switch to `coinbrew`, everything should be good.

**Comment by tkralphs** [comment]
I'm going to close for now, feel free to re-open.

**Comment by casper-murtonen** [comment]
I was perhaps naively following the instructions online and in the pdf manual for 5.6.17.  Afterwards I did see the instructions re coinbrew in README.md but from the wording it seemed to me that coinbrew is an interim measure, whilst issues in coin.install.sh are being resolved.

So SYMPHONY 5.6 as fetched by coinbrew does not have this issue.  The version of Osi it uses does not reference Glpk glp_get_it_cnt().

SYMPHONY as fetched by coin.install.sh appears to use a more recent version of Osi which is where the issue arises.  I guess this is one of the inconsistencies to be resolved.

**Comment by tkralphs** [comment]
I apologize for the goose chase. We are in a long period of transition across many COIN-OR projects and fighting a never-ending game of whack-a-mole against out-of-date documentation. If you could point out any documentation that seems out-of-date or misleading, that would be appreciated. I had thought everything was pretty up-to-date with SYMPHONY, but apparently not! I'm surprised that coin.install.sh got a wrong version of Osi, but in any case, coinbrew is the permanent solution that I'm actively maintaining. I should probably update it to just output a message that it is deprecated, as you are not the only one who has stumbled upon it in recent times. 

At the moment, I'm trying to get SYMPHONY master to work with our new build harness and to merge in a bunch of changes from a few different branches, then there will be a new 6.0 version of SYMPHONY. In the meantime, I'm happy to make a new release of stable/5.6 to update documentation in order to avoid more confusion. 

Thanks for the report!

**Comment by casper-murtonen** [comment]
For me perhaps one of the strengths of SYMPHONY over other projects is that there is a useful manual.  I cannot understate how useful it is that SYMPHONY has a manual that covers the API rather than being just a bunch of sparsely documented source code, whether or not formatted for Doxygen.  SYMPHONY actually works rather well too.

In any case I referred to the wrong files for instructions - the manual and the INSTALL text file which both referred to the coin.install.sh method of fetching and building.  It may be simple to remove the outdated INSTALL file and leave just the current INSTALL.md file, and perhaps more involved to update the 5.6.17 pdf manual.

**Comment by tkralphs** [comment]
Ah, I see. Yes, I will update the manual and make a new release. I had forgotten that the manual was still talking about `coin.install.sh`. Unfortunately, I can't seem to build a new HTML version, as latex2html no longer works for some reason I can't easily debug. Maybe I'll just edit the HTML files by hand. 

It is gratifying to hear that someone appreciates the detailed manual and is using the code successfully. I don't get a lot of feedback, so thank you! That provides a little additional motivation to do the maintenance work. Look out for SYMPHONY 6.0 "soon" :).
