### ISSUE TITLE
gap_limit parameter query

### ISSUE THREAD

**Issue by jeffreyhanson** [coin-or/SYMPHONY#177]
Thank you so much for developing the SYMPHONY software! If you have a moment, I wanted to ask a question about the `gap_limit` parameter? The [documentation]( https://www.coin-or.org/SYMPHONY/doc/SYMPHONY-5.6.9-Manual.pdf) states that:

> gap limit – double (-1.0). Target gap limit allowed for solution. When the gap between the
lower and the upper bound reaches this point, the solution process will stop and the best
solution found to that point, along with other relevant data, will be output. A gap limit less
than 0 means there is no limit.

Since the documentation does not mention that the `gap_limit` parameter is a percentage or relative value, I would interpret this parameter to relate to the absolute difference between the lower and upper bound. In other words, if I set a `gap_limit` value of 1, I would expect to SYMPHONY to stop the solution process when `UB - LB <= 1`. However, the SYMPHONY documentation also states that:

 > A new feature in SYMPHONY 5.6.9 is the ability to stop the computation based on exceeding
a given time limit, exceeding a given limit on the number of processed nodes, achieving a target
percentage gap between the upper and lower bounds, or finding the first feasible solution.

I'm sorry if I missed something obvious, but I couldn't find any parameter describing such a "target percentage gap" when looking through the documentation. Does this mean that the `gap_limit` tells the solution process to stop based on a target percentage gap? In other words, does it tell the solution process to stop when `((UB - LB) / UB) * 100 <= gap_limit`? I tried playing around with different UB, LB, and Gap values printed out when running SYMPHONY and it would appear that this is the case, but I just wanted to double check in case I'm missing something?

**Comment by tkralphs** [comment]
Yes, sorry that confusion. "The gap" is a relative gap by default in the optimization literature (ass opposed to an absolute gap), so it's easy to forget to define it rigorously. Absolute gap is not something typically very useful because it is not scale-invariant whereas the objective function itself can be scaled without changing the set of optimal solutions. For the definition and use of gap in the code, see here

https://github.com/coin-or/SYMPHONY/blob/96c909d347579c491ed3ba0ba7531c0214bb0ba5/src/Common/sym_qsort.c#L109

and here

https://github.com/coin-or/SYMPHONY/blob/96c909d347579c491ed3ba0ba7531c0214bb0ba5/src/TreeManager/tm_func.c#L505

I've got some other issues to address in the documentation and have been waiting to find some time to get to it, so if you leave this issue open, I'll try to make that change when I have the chance.

**Comment by jeffreyhanson** [comment]
Brilliant - thank you very much for clarifying that. Yeah, I can leave the issue open. If the documentation is in the repo, I would be happy to submit a PR if that would be helpful?

**Comment by tkralphs** [comment]
The documentation is indeed in the repo in the `Doc` subdirectory in `master` or `SYMPHONY/Doc` in `stable/5.6` (I recently reorganized the directory structure a bit). The documentation is in LaTex, you'll have to grep for the right file to edit. Thanks!

**Comment by jeffreyhanson** [comment]
Ok - excellent! I'll try and submit the PR sometime tomorrow.
