### ISSUE TITLE
Osi Solver Interface will skip problem loading when the matrix is empty

### ISSUE THREAD

**Issue by yuxies** [coin-or/SYMPHONY#193]
Found when testing bilevel instances without any lower level constraints:

- When the input matrix has zero row# and column#, the interface will stop loading [here](https://github.com/coin-or/SYMPHONY/blob/master/src/OsiSym/OsiSymSolverInterface.cpp#L873), print out the warning, and then return to the previous layer on the call stack.
- Because of this early return, no information can be sent to SYMPHONY to construct the problem, resulting in null pointers in SYMPHONY presolve.

**Comment by tkralphs** [comment]
Actually, this is kind of a problem with the API of Osi. In this particular function call, the only way of getting the number of columns is by querying the dimensions of the matrix. Even if there are bounds on the variables and we want to solve the MILP using just those box constraints, it's not really possible through this interface.  

But the `loadProblem` method is overloaded and there are some other variants that we would need to use if we detect that the matrix is empty. In any case, we should verify that the dimensions of the matrix actually match the dimensions of the vectors of variable bounds. 

It looks like we eventually drop into a call to `sym-explicit_load_problem`, which does seem to handle problem with only box constraints correctly. So this nothing that can really be fixed by a change to SYMPHONY.
