### ISSUE TITLE
5.7.0: 2 errors and 5 warnings during tests

### ISSUE THREAD

**Issue by yurivict** [coin-or/SYMPHONY#195]
Please see the 5.7.0 log [here](https://people.freebsd.org/~yuri/symphony-5.7.0-test.log).
```
Severity NOTE      :    7  thereof expected:    6
Severity PASSED    : 1141  thereof expected:    0
Severity WARNING   :    5  thereof expected:    0
Severity ERROR     :    2  thereof expected:    0
Tests completed with 2 unexpected errors.
```

Version 5.6.19 didn't have such errors and warnings:
```
Severity NOTE      :    0  thereof expected:    0
Severity PASSED    :  683  thereof expected:    0
Severity WARNING   :    0  thereof expected:    0
Severity ERROR     :    0  thereof expected:    0
All tests completed successfully
```

clang-14
FreeBSD 13.1

**Comment by tkralphs** [comment]
Thanks and sorry for the delay in responding. I saw this error with automated builds on another platform, but haven't been able to replicate locally. The error is actually because of a tolerance issue with Clp. As such, it's not really a SYMPHONY issue and the failures are actually with the solution of LPs, which are being solved through SYMPHONY's interface. The test that's being done is not really part of the suite I would normally do, but the Netlib instances are being automatically incorporated due to the presence of the Netlib data set. Building with `--without-netlib` will cause the netlib test not to be done.  

Anyway, since the underlying LP solver is Clp, this is something that should have been caught in testing Clp. but Clp's tests seem to be passing. Even with SYMPHONY, the solution Clp is returning is "correct," but the objective value is not within the tolerance set by SYMPHONY for the test. It could simply be that Clp is using a different tolerance in its tests. I'll check into that.

The comparison with 5.6.19 is interesting, since the tests run should be exactly the same. It seems 5.7.0 is doing many more tests, though. Were the `5.6.19` runs done with exactly the same versions of dependencies as with 5.7.0 or were these done in the past? 

Thanks for reporting, I will poke at this.

**Comment by tkralphs** [comment]
OK, I was now able to replicate this. It's very strange, since it even happens when I build both 5.7.0 and 5.6.19 with exactly the same dependencies and the same Clp version. Off the top of my head, I don't see why there would be any difference between the two versions in this case. But I at least now have something to dig my teeth into.

**Comment by tkralphs** [comment]
There was a minor change to the code between 5.6 and 5.7 that re-introduced LP presolve. This was previously found to reult in some numerical issues, which is why it was disabled in 5.6. Although the numerical issues are most likely inconsequential, I have disabled pre-processing again. There were also some common unit tests enabled that are menat for LP solvers through their Osi interface that really don't apply to MILP solvers and I have disabled those. Now the unit test outcomes for 5.6 and 5.7 are identical, as expected. I'll put out a new release shortly.
