### ISSUE TITLE
Building of "Applications" does not seem to work anymore

### ISSUE THREAD

**Issue by sschnug** [coin-or/SYMPHONY#9]
While trying to get a look into Symphony, i tried to build the example applications (and i read all the INSTALL files and some mailing-list discussions).

Without any idea about the hierarchy & build-system i think:

- (At least) Symphony >= 5.5 never builds *libSymAppl* (even with ```--with-application```)
- All those Application Makefiles still want to link against it! -> *Failing!*

I needed to go back as far as Symphony 5.4, where ```--with-application``` actually makes a difference.

(Bonus-remark: ```--with-application``` is never documented with ```configure -h```; this applies to 5.4 too)

**Comment by tkralphs** [comment]
I was able to replicate this. In fact, ```libSymAppl``` is getting _built_, just not installed (the first time). It should work if you run ```make install``` twice (or configure with ```--disable-dependency-linking```). 

The long explanation is that at some point, I changed the installation process so that libraries are linked against dependencies at build time to check that all dependencies are present (this is a best practice). This required creating a library of stub functions (a fake application) to allow the application library to link properly. This library is called ```libSymApplStubs```. It seems the stubs library is getting installed after ```libSymAppl``` so the linking step is failing initially for ```libSymAppl```. Running ```make install``` twice works because the second time, ```libSymApplStubs``` has already been installed the first time and the linking succeeds. Configuring with ```--disable-dependency-linking``` skips the test linkingand should allow everything to go through fine.

I'll fix this, but there is a workaround anyway. Thanks for pointing this out!

**Comment by tkralphs** [comment]
Oh, and I forgot to say that `configure -h` does actually mention `--with-application`, but only if you run it with the configure script in the `SYMPHONY` subdirectory (I believe this has always been the case). This is an artifact of the original build system design in which the root configure script is just for detecting the presence of dependencies and setting up the recursive build. Individual components have their own `configure` scripts (SYMPHONY pulls in some components from other projects using `svn`'s externals mechanism). Unfortunately, although the `configure` script itself is set up to be used recursively (it passes parameters down to lower-level `configure` scripts), the help is not recursive. 

This is all set to change at some point in the future once I get a bit of time. The root configure will go away and everything will be a bit more intuitive. This is part of the eventual move to git, which doesn't really have a notion of externals.

**Comment by tkralphs** [comment]
This should be fixed by d01c075046.
